name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "stable"
          cache-dependency-path: go.sum

      - name: golangci-lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run ./...


