name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "stable"
          cache-dependency-path: go.sum

      - name: golangci-lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run ./...


