name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "stable"
          cache-dependency-path: go.sum

      - name: golangci-lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run ./...


